### ISSUE TITLE
Unify version style in Cargo.tom

### ISSUE THREAD

**Issue by rustdesk** [snooowfire/ironhive#1]
![image](https://github.com/snooowfire/ironhive/assets/71636191/b16d7e5f-2dab-4a74-9099-685cb84bb0a4)

All use "x.x" style. e.g. tokio = { "version" = "1.33" }

**Comment by snooowfire** [comment]
![image](https://github.com/snooowfire/ironhive/assets/147996737/61e7e453-a3bb-47e8-8d0f-f2abb0609be2)
