### ISSUE TITLE
How to give remote command to the agent?

### ISSUE THREAD

**Issue by mocusez** [snooowfire/ironhive#10]
Could you please write a example about how to give remote command to the agent?
It's ok you have test, but it seems to be better to give a full instruction book and details with different arguments
![image](https://github.com/snooowfire/ironhive/assets/57286919/d315aea9-0e71-4f8d-bb46-68e229797b18)

**Comment by snooowfire** [comment]
The entire agent consists of only one RPC service used to handle NATS messages. If you want to perform remote control, you can only do so by sending NATS requests to the NATS server. For specific requests, you can refer to the following location: [crates/shared/src/request.rs](https://github.com/snooowfire/ironhive/blob/594ee576db5df46b35e8be601bf6039568b09b41/crates/shared/src/request.rs#L13).

To understand how to make requests, you can refer to the test case below:

```rust
client
    .publish_with_reply(agent_id.to_string(), "your_reply".into(), IronhiveRequest::Ping.as_bytes())
    .await
    .unwrap();
```

This code snippet demonstrates an example of making a request. The `client.publish_with_reply` function is used to publish a NATS message with a reply subject and payload. In this case, the request being sent is `IronhiveRequest::Ping`.

Additionally, I have updated the installation instructions in the README. I hope you can take a look at it.

**Comment by mocusez** [comment]
Something is confused:
Is that agent ID generate by agent, or NATS server?
I remember that publish_with_reply need to give a certain channel name

————Updated：
Ok, I get AgentID from nats-top
I believe this must be mention on document

**Comment by mocusez** [comment]
![image](https://github.com/snooowfire/ironhive/assets/57286919/626e3293-5bd3-4a24-b164-1070cbb8f302)

**Comment by mocusez** [comment]
JavaScript Running is OK.
This issue will be close.
![985d58932c228649f878d60c0b35ab3](https://github.com/snooowfire/ironhive/assets/57286919/cc2c60d7-6097-4c41-a246-9e0007fb8bf8)
