### ISSUE TITLE
Add default attribute to all field for deserialize 

### ISSUE THREAD

**Issue by rustdesk** [snooowfire/ironhive#2]
![image](https://github.com/snooowfire/ironhive/assets/71636191/2ede39d5-005b-4011-92a5-49d13e2d97ab)

It will have better compatibility. e.g. server side sends to agent a message missing some fields.

![image](https://github.com/snooowfire/ironhive/assets/71636191/60dcb831-ff3b-4dc1-9c99-547a406b28b2)

**Comment by snooowfire** [comment]
I have divided this issue into two parts for handling. The first part involves the crate itself requiring deserialization. I have set defaults for certain optional fields, while fields without defaults need to be specified. 

![image](https://github.com/snooowfire/ironhive/assets/147996737/4cb7bd6b-472c-4308-956c-abeceb198685)

The second part pertains to deserialization not currently used in the crate, but there may be future requirements for data structures when others use this crate. To address this, I have added a feature called "deserialize" that can be enabled. By default, it is disabled.

![image](https://github.com/snooowfire/ironhive/assets/147996737/ed447729-523f-4c08-8209-71a32961b8c3)
