### ISSUE TITLE
fmt

### ISSUE THREAD

**Issue by rustdesk** [snooowfire/ironhive#5]
![image](https://github.com/snooowfire/ironhive/assets/71636191/d8d0f052-ce05-4668-b1fc-f1a52175e743)

unified new line style, and the other fmt etc.

`cargo fmt` may help you, that's why we need add cargo fmt into github ci.

**Comment by snooowfire** [comment]
yes
![image](https://github.com/snooowfire/ironhive/assets/147996737/86c6d6e2-1f88-4917-af63-5c06c1c7eca7)
