### ISSUE TITLE
Initial fail on Windows 10

### ISSUE THREAD

**Issue by mocusez** [snooowfire/ironhive#9]
## Description
I follow the instruct says:

```shell
ironhive install --nats-servers <NATS_SERVERS>
```

Replace `<NATS_SERVERS>` with the list of NATS server addresses you want to connect to.

But it seems is not work, I'm trying to figure out what might be wrong.

![image](https://github.com/snooowfire/ironhive/assets/57286919/fdd427cd-81ec-4570-af31-d385e219c8f3)

**Comment by mocusez** [comment]
By the way, can you give me a example on how to give order to the agent?

**Comment by snooowfire** [comment]
fix by eb2daaf26680208241dfae376a28e0e3664e7cb5

**Comment by snooowfire** [comment]
https://github.com/snooowfire/ironhive?tab=readme-ov-file#usage

**Comment by mocusez** [comment]
I'm sorry I didn't make myself clear😰, please see #10
